# Generated by Django 5.1.4 on 2025-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
