# Generated by Django 5.1.4 on 2025-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price_course_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='sale_price',
            field=models.FloatField(),
        ),
    ]
