# Generated by Django 5.1.3 on 2025-02-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_bankinfo_paymentbankinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbankinfo',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='business.bankinfo'),
        ),
    ]
