# Generated by Django 5.1.3 on 2025-02-08 12:58

import apis.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.CharField(default=apis.orders.models.generate_short_uuid, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_upload', 'Pending upload'), ('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted')], default='pending_upload', max_length=20),
        ),
    ]
