# Generated by Django 5.1.4 on 2025-02-14 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_price_alter_course_sale_price'),
        ('orders', '0003_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
